specification: .circleci/specifications/stripe-api.yml
outputDir: stripe
packageName: stripeapi
moduleName: StripeAPI
logLevel: WARN
force: false
incremental: true
dryRun: false
doNotGenerateStackProject: false
generateNixFiles: false
omitAdditionalOperationFunctions: true
generateOptionalEmptyRequestBody: false
useNumberedVariantConstructors: false
useFloatWithArbitraryPrecision: false
useIntWithArbitraryPrecision: false
useDateTypesAsString: false
convertToCamelCase: true
propertyTypeSuffix: "'"
responseTypeSuffix: "Response"
responseBodyTypeSuffix: "ResponseBody"
requestBodyTypeSuffix: "RequestBody"
parametersTypeSuffix: "Parameters"
parameterQueryPrefix: "query"
parameterPathPrefix: "path"
parameterCookiePrefix: "cookie"
parameterHeaderPrefix: "header"
operationsToGenerate: []
opaqueSchemas: []
whiteListedSchemas: []