resolver: lts-18.16
packages:
- openapi3-code-generator
nix:
  shell-file: shell.nix
extra-deps:
- github: NorfairKing/autodocodec
  commit: f0cb2ead0985b4394db0627e6befd7ce23c54c22
  subdirs:
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml
- github: NorfairKing/safe-coloured-text
  commit: bd8700a555e977004e2dec24e12494a5a01ca500
  subdirs:
  - safe-coloured-text
