name: official-petstore
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - http-client
  - http-conduit
  - bytestring
  - text
  - openapi
  - level2-base

library:
  source-dirs: src

tests:
  official-petstore-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - official-petstore
      - hspec
      - transformers
      - http-types
