version: 2

defaults: &defaults
  docker:
    - image: joelfisch/stack-with-prebuilt-deps:latest
  working_directory: /mnt/ramdisk
  resource_class: xlarge

jobs:
  lint:
    <<: *defaults
    docker:
      - image: joelfisch/hlint:latest
    steps:
      - checkout
      - run:
          name: Lint
          command: ./.circleci/lint_generator

  test-and-coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Tests and coverage
          command: ./.circleci/coverage
      - store_artifacts:
          path: ./openapi3-code-generator/coverage-output

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: ./.circleci/build_generator
      - persist_to_workspace:
          root: /mnt/ramdisk
          paths: .

  golden:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk
      - run:
          name: Golden tests
          command: ./.circleci/test_golden

  system1:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk
      - run:
          name: System tests level 1
          command: ./.circleci/test_system_1

  system2:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk
      - run:
          name: System tests level 2
          command: ./.circleci/test_system_2

  system3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk
      - run:
          name: System tests level 3
          command: ./.circleci/test_system_3

  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk
      - run:
          name: System tests level 3
          command: ./.circleci/test_system_3

workflows:
  version: 2
  all:
    jobs:
      - lint
      - test-and-coverage
      - build
      - golden:
          requires:
            - build
      - system1:
          requires:
            - build
      - system2:
          requires:
            - build
      - system3:
          requires:
            - build
