version: 2

defaults: &defaults
  docker:
    - image: joelfisch/stack-with-prebuilt-deps:v0.0.7
  working_directory: ~/project

jobs:
  lint:
    docker:
      - image: joelfisch/hlint:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Lint
          command: ./.circleci/lint_generator

  test-and-coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Tests and coverage
          command: ./.circleci/coverage
      - store_artifacts:
          path: ./openapi3-code-generator/coverage-output

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: ./.circleci/build_generator
      - persist_to_workspace:
          root: ~/project
          paths: .

  golden:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Golden tests
          command: ./.circleci/test_golden

  system1:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: System tests level 1
          command: ./.circleci/test_system_1

  system1_lts19-10:
    docker:
      - image: joelfisch/stack-with-prebuilt-deps:lts-19.10
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: System tests level 1 (LTS 19.10)
          command: ./.circleci/test_system_1_lts-19-10

  system2:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: System tests level 2
          command: ./.circleci/test_system_2

  system2stripe:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: System tests level 2 (Stripe)
          command: ./.circleci/test_system_2_stripe

  system3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: System tests level 3
          command: |
            cd .circleci/testing/level3/mock-server
            stack build
            stack run &
            cd ~/project
            ./.circleci/test_system_3

workflows:
  version: 2
  all:
    jobs:
      - lint
      - test-and-coverage
      - build
      - golden:
          requires:
            - build
      - system1:
          requires:
            - build
      - system1_lts19-10:
          requires:
            - build
      - system2:
          requires:
            - build
      - system2stripe:
          requires:
            - build
      - system3:
          requires:
            - build
