name:                level2-base
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- http-types
- http-client
- http-conduit
- bytestring
- openapi

library:
  source-dirs: src
