name: "Build nix derivations"
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#devShells.x86_64-linux.default
          - .#packages.x86_64-linux.default
          - .#checks.x86_64-linux.pre-commit
          - .#checks.x86_64-linux.test-golden
          - .#checks.x86_64-linux.test-golden-generate
          - .#checks.x86_64-linux.test-system-1
          - .#checks.x86_64-linux.test-system-2
          - .#checks.x86_64-linux.test-system-3
    steps:
    - uses: actions/checkout@v2.5.0
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
    - name: free disk space
      run: |
        if [[ "${{matrix.os}}" == "ubuntu-latest" ]]
        then
          sudo rm -rf /opt
        fi
    - uses: cachix/cachix-action@v11
      with:
        name: openapi3-code-generator
        extraPullNames: validity,safe-coloured-text,sydtest,autodocodec
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build "${{matrix.attribute}}"
